// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using tashrif.Context;

#nullable disable

namespace tashrif.Context.Migrations
{
    [DbContext(typeof(tashrifDBContext))]
    [Migration("20260913021855_AddMustChangePassword")]
    partial class AddMustChangePassword
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("tashrif.Data.applications", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("cover_letter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("cv_id")
                        .HasColumnType("bigint");

                    b.Property<string>("experience")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("job_id")
                        .HasColumnType("bigint");

                    b.Property<string>("qualification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("cv_id");

                    b.HasIndex("job_id");

                    b.HasIndex("user_id");

                    b.ToTable("applications");
                });

            modelBuilder.Entity("tashrif.Data.bank_accounts", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("account_status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("bank_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("iban")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("iban_status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("user_id");

                    b.ToTable("bank_accounts");
                });

            modelBuilder.Entity("tashrif.Data.contact_persons", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("entity_id")
                        .HasColumnType("bigint");

                    b.Property<bool>("is_primary")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nationality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("entity_id");

                    b.ToTable("contact_persons");
                });

            modelBuilder.Entity("tashrif.Data.contracts", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("application_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("entity_id")
                        .HasColumnType("bigint");

                    b.Property<long?>("file_size")
                        .HasColumnType("bigint");

                    b.Property<string>("file_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("job_id")
                        .HasColumnType("bigint");

                    b.Property<string>("notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("signed_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("application_id");

                    b.HasIndex("entity_id");

                    b.HasIndex("job_id");

                    b.HasIndex("user_id");

                    b.ToTable("contracts");
                });

            modelBuilder.Entity("tashrif.Data.cvs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("file_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("file_path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("file_size")
                        .HasColumnType("bigint");

                    b.Property<bool>("is_default")
                        .HasColumnType("boolean");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("user_id");

                    b.ToTable("cvs");
                });

            modelBuilder.Entity("tashrif.Data.entity_profiles", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("commercial_reg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("company_desc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("company_field")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("company_size")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("district")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("facebook_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("logo_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("profile_completion_pct")
                        .HasColumnType("smallint");

                    b.Property<string>("province")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sector")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("twitter_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.Property<string>("website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("youtube_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("zipcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("zone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("user_id");

                    b.ToTable("entity_profiles");
                });

            modelBuilder.Entity("tashrif.Data.experiences", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("duration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("employer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_current")
                        .HasColumnType("boolean");

                    b.Property<string>("job_title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("start_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("user_id");

                    b.ToTable("experiences");
                });

            modelBuilder.Entity("tashrif.Data.individual_profiles", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("birth_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cv_file")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("district")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("id_file")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("job_title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("profile_completion_pct")
                        .HasColumnType("smallint");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.Property<string>("zipcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("zone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("user_id");

                    b.ToTable("individual_profiles");
                });

            modelBuilder.Entity("tashrif.Data.interviews", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("application_id")
                        .HasColumnType("bigint");

                    b.Property<string>("attendance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("entity_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("interview_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("interview_time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("job_id")
                        .HasColumnType("bigint");

                    b.Property<string>("link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("application_id");

                    b.HasIndex("entity_id");

                    b.HasIndex("job_id");

                    b.HasIndex("user_id");

                    b.ToTable("interviews");
                });

            modelBuilder.Entity("tashrif.Data.job_benefits", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("benefit_text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("job_id")
                        .HasColumnType("bigint");

                    b.Property<short>("sort_order")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("job_id");

                    b.ToTable("job_benefits");
                });

            modelBuilder.Entity("tashrif.Data.job_conditions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("condition_text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("job_id")
                        .HasColumnType("bigint");

                    b.Property<short>("sort_order")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("job_id");

                    b.ToTable("job_conditions");
                });

            modelBuilder.Entity("tashrif.Data.job_responsibilities", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("job_id")
                        .HasColumnType("bigint");

                    b.Property<string>("responsibility_text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("sort_order")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("job_id");

                    b.ToTable("job_responsibilities");
                });

            modelBuilder.Entity("tashrif.Data.jobs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("duration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("entity_id")
                        .HasColumnType("bigint");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("hours")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("publish_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("qualification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("salary_max")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("salary_min")
                        .HasColumnType("numeric");

                    b.Property<string>("salary_text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("target")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("vacancies")
                        .HasColumnType("integer");

                    b.Property<string>("work_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("entity_id");

                    b.ToTable("jobs");
                });

            modelBuilder.Entity("tashrif.Data.qualifications", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("grade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short?>("graduation_year")
                        .HasColumnType("smallint");

                    b.Property<string>("institution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("user_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("user_id");

                    b.ToTable("qualifications");
                });

            modelBuilder.Entity("tashrif.Data.users", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("avatar_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("must_change_password")
                        .HasColumnType("boolean");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("national_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nationality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("tashrif.Data.applications", b =>
                {
                    b.HasOne("tashrif.Data.cvs", "cv_Entity")
                        .WithMany()
                        .HasForeignKey("cv_id");

                    b.HasOne("tashrif.Data.jobs", "job_Entity")
                        .WithMany()
                        .HasForeignKey("job_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tashrif.Data.users", "user_Entity")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cv_Entity");

                    b.Navigation("job_Entity");

                    b.Navigation("user_Entity");
                });

            modelBuilder.Entity("tashrif.Data.bank_accounts", b =>
                {
                    b.HasOne("tashrif.Data.users", "user_Entity")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user_Entity");
                });

            modelBuilder.Entity("tashrif.Data.contact_persons", b =>
                {
                    b.HasOne("tashrif.Data.entity_profiles", "entity_Entity")
                        .WithMany()
                        .HasForeignKey("entity_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("entity_Entity");
                });

            modelBuilder.Entity("tashrif.Data.contracts", b =>
                {
                    b.HasOne("tashrif.Data.applications", "application_Entity")
                        .WithMany()
                        .HasForeignKey("application_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tashrif.Data.users", "entity_Entity")
                        .WithMany()
                        .HasForeignKey("entity_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tashrif.Data.jobs", "job_Entity")
                        .WithMany()
                        .HasForeignKey("job_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tashrif.Data.users", "user_Entity")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("application_Entity");

                    b.Navigation("entity_Entity");

                    b.Navigation("job_Entity");

                    b.Navigation("user_Entity");
                });

            modelBuilder.Entity("tashrif.Data.cvs", b =>
                {
                    b.HasOne("tashrif.Data.users", "user_Entity")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user_Entity");
                });

            modelBuilder.Entity("tashrif.Data.entity_profiles", b =>
                {
                    b.HasOne("tashrif.Data.users", "user_Entity")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user_Entity");
                });

            modelBuilder.Entity("tashrif.Data.experiences", b =>
                {
                    b.HasOne("tashrif.Data.users", "user_Entity")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user_Entity");
                });

            modelBuilder.Entity("tashrif.Data.individual_profiles", b =>
                {
                    b.HasOne("tashrif.Data.users", "user_Entity")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user_Entity");
                });

            modelBuilder.Entity("tashrif.Data.interviews", b =>
                {
                    b.HasOne("tashrif.Data.applications", "application_Entity")
                        .WithMany()
                        .HasForeignKey("application_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tashrif.Data.users", "entity_Entity")
                        .WithMany()
                        .HasForeignKey("entity_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tashrif.Data.jobs", "job_Entity")
                        .WithMany()
                        .HasForeignKey("job_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tashrif.Data.users", "user_Entity")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("application_Entity");

                    b.Navigation("entity_Entity");

                    b.Navigation("job_Entity");

                    b.Navigation("user_Entity");
                });

            modelBuilder.Entity("tashrif.Data.job_benefits", b =>
                {
                    b.HasOne("tashrif.Data.jobs", "job_Entity")
                        .WithMany()
                        .HasForeignKey("job_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("job_Entity");
                });

            modelBuilder.Entity("tashrif.Data.job_conditions", b =>
                {
                    b.HasOne("tashrif.Data.jobs", "job_Entity")
                        .WithMany()
                        .HasForeignKey("job_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("job_Entity");
                });

            modelBuilder.Entity("tashrif.Data.job_responsibilities", b =>
                {
                    b.HasOne("tashrif.Data.jobs", "job_Entity")
                        .WithMany()
                        .HasForeignKey("job_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("job_Entity");
                });

            modelBuilder.Entity("tashrif.Data.jobs", b =>
                {
                    b.HasOne("tashrif.Data.users", "entity_Entity")
                        .WithMany()
                        .HasForeignKey("entity_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("entity_Entity");
                });

            modelBuilder.Entity("tashrif.Data.qualifications", b =>
                {
                    b.HasOne("tashrif.Data.users", "user_Entity")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user_Entity");
                });
#pragma warning restore 612, 618
        }
    }
}
