<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>9e397b1b-191a-46b5-bdcf-75d8afb67f1d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Business\tashrif.Core\tashrif.Core.csproj" />
    <ProjectReference Include="..\..\Business\tashrif.Email\tashrif.Email.csproj" />
    <ProjectReference Include="..\..\Business\tashrif.Identity\tashrif.Identity.csproj" />
    <ProjectReference Include="..\..\Business\tashrif.Subscription\tashrif.Subscription.csproj" />
    <ProjectReference Include="..\..\Business\tashrif.Shared\tashrif.Shared.csproj" />
    <ProjectReference Include="..\..\Business\tashrif.Support\tashrif.Support.csproj" />
    <ProjectReference Include="..\..\Business\tashrif.Tenant\tashrif.Tenant.csproj" />
    <ProjectReference Include="..\..\Domain\tashrif.Data\tashrif.Data.csproj" />
    <ProjectReference Include="..\..\Domain\tashrif.Context\tashrif.Context.csproj" />
    <ProjectReference Include="..\..\Infrastructure\tashrif.Repository\tashrif.Repository.csproj" />
  </ItemGroup>

</Project>
